### ISSUE TITLE
路径获取错误，盘符重复

### ISSUE THREAD

**Issue by qxchuckle** [Simon-He95/export-what#2]
如下图，盘符重复导致插件不起作用

![image](https://github.com/Simon-He95/export-what/assets/55614189/e5e0d8d2-a9e1-4786-9f11-2bb17db1a41e)

**Comment by Simon-He95** [comment]
看样子似乎是windows电脑上路径可能处理的有问题，我没有windows电脑，你试一下最新版本的插件是否可以解决:), 不行的话，有兴趣的话可以尝试提一个pr
